/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return server and model status.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Message
         * @description Classify a customer message and persist the resulting ticket.
         */
        post: operations["classify_message_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClassifyRequest
         * @description POST /classify request body.
         */
        ClassifyRequest: {
            /** Message */
            message: string;
        };
        /**
         * ClassifyResponse
         * @description POST /classify response body.
         */
        ClassifyResponse: {
            /** Intent */
            intent: string;
            /** Confidence */
            confidence: number;
            /** Top K */
            top_k: components["schemas"]["IntentScore"][];
            ticket: components["schemas"]["Ticket"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntentScore
         * @description A single (intent, confidence) pair in the top-k list.
         */
        IntentScore: {
            /** Intent */
            intent: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * Ticket
         * @description The structured ticket persisted and returned to the client.
         */
        Ticket: {
            /** Id */
            id: string;
            /** Department */
            department: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "P1" | "P2" | "P3";
            /** Sla Hours */
            sla_hours: number;
            /** Tags */
            tags: string[];
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    classify_message_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
