"""Pydantic models: API contracts and internal domain types.

Single source of truth for typed data flowing through the system. The OpenAPI
schema generated by FastAPI from these models is the basis for the frontend's
generated TypeScript types — see architecture section 4.

API-facing models:
- ClassifyRequest / ClassifyResponse — POST /classify body and result.
- IntentScore                        — one row of the top-k list.
- Ticket                             — the structured ticket.
- ErrorResponse                      — the canonical error body.

Internal domain models (not directly exposed at HTTP boundary):
- Prediction                         — output of predict.classify().
- RoutingRule                        — one row of configs/routing.yaml.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator

# ---------------------------------------------------------------------------
# Shared field types
# ---------------------------------------------------------------------------

Priority = Literal["P1", "P2", "P3"]


def _serialize_utc_z(dt: datetime) -> str:
    """Serialize a UTC datetime to an ISO 8601 string with `Z` suffix."""
    if dt.tzinfo is None:
        # Should not happen — Ticket validates tz-awareness — but be defensive.
        return dt.isoformat() + "Z"
    return dt.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


# ---------------------------------------------------------------------------
# API-facing models
# ---------------------------------------------------------------------------


class ClassifyRequest(BaseModel):
    """POST /classify request body."""

    model_config = ConfigDict(protected_namespaces=("settings_",))

    message: Annotated[str, Field(min_length=1, max_length=1000)]


class IntentScore(BaseModel):
    """A single (intent, confidence) pair in the top-k list."""

    intent: Annotated[str, Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class Ticket(BaseModel):
    """The structured ticket persisted and returned to the client."""

    id: Annotated[str, Field(min_length=26, max_length=26)]
    department: Annotated[str, Field(min_length=1)]
    priority: Priority
    sla_hours: Annotated[int, Field(gt=0)]
    tags: Annotated[list[str], Field(min_length=1, max_length=10)]
    created_at: datetime

    @field_validator("created_at")
    @classmethod
    def _require_tz_aware(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("created_at must be timezone-aware (UTC)")
        return v

    @field_validator("tags")
    @classmethod
    def _no_empty_tags(cls, v: list[str]) -> list[str]:
        if any(not t.strip() for t in v):
            raise ValueError("tags must not contain empty strings")
        return v

    @field_serializer("created_at")
    def _serialize_created_at(self, v: datetime) -> str:
        return _serialize_utc_z(v)


class ClassifyResponse(BaseModel):
    """POST /classify response body."""

    intent: Annotated[str, Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    top_k: Annotated[list[IntentScore], Field(min_length=3, max_length=3)]
    ticket: Ticket


# ---------------------------------------------------------------------------
# Internal domain models
# ---------------------------------------------------------------------------


class Prediction(BaseModel):
    """Result of the inference pipeline (predict.classify)."""

    intent: Annotated[str, Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    top_k: Annotated[list[IntentScore], Field(min_length=3, max_length=3)]


class RoutingRule(BaseModel):
    """One row of configs/routing.yaml."""

    intent: Annotated[str, Field(min_length=1)]
    department: Annotated[str, Field(min_length=1)]
    priority: Priority
    sla_hours: Annotated[int, Field(gt=0)]
    tags: Annotated[list[str], Field(min_length=1, max_length=10)]


# ---------------------------------------------------------------------------
# Error envelope
# ---------------------------------------------------------------------------


class _ErrorBody(BaseModel):
    code: str
    message: str
    correlation_id: str | None = None


class ErrorResponse(BaseModel):
    """The canonical error response body returned for every 4xx and 5xx.

    Shape: ``{ "error": { "code", "message", "correlation_id" } }``.
    """

    error: _ErrorBody

    @classmethod
    def from_parts(
        cls,
        *,
        code: str,
        message: str,
        correlation_id: str | None,
    ) -> ErrorResponse:
        return cls(error=_ErrorBody(code=code, message=message, correlation_id=correlation_id))
